provider: linode
major-version: 4
env:
  LINODE_TOKEN: ${{ secrets.LINODE_API_TOKEN }}
makeTemplate: bridged
pulumiConvert: 1
registryDocs: true
plugins:
  - name: std
    version: "1.6.2"

  - name: terraform
    version: "1.0.16"
    kind: converter
