// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.linode.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.linode.inputs.GetConsumerImageShareGroupImageSharesImageShareImageSharingSharedBy;
import com.pulumi.linode.inputs.GetConsumerImageShareGroupImageSharesImageShareImageSharingSharedWith;
import java.util.Objects;


public final class GetConsumerImageShareGroupImageSharesImageShareImageSharing extends com.pulumi.resources.InvokeArgs {

    public static final GetConsumerImageShareGroupImageSharesImageShareImageSharing Empty = new GetConsumerImageShareGroupImageSharesImageShareImageSharing();

    /**
     * (Nested Attribute) Details about who the image is shared by. Referenced directly (e.g. `shared_by.sharegroup_id`).
     * 
     */
    @Import(name="sharedBy", required=true)
    private GetConsumerImageShareGroupImageSharesImageShareImageSharingSharedBy sharedBy;

    /**
     * @return (Nested Attribute) Details about who the image is shared by. Referenced directly (e.g. `shared_by.sharegroup_id`).
     * 
     */
    public GetConsumerImageShareGroupImageSharesImageShareImageSharingSharedBy sharedBy() {
        return this.sharedBy;
    }

    /**
     * (Nested Attribute) Details about who the image is shared with. Referenced directly (e.g. `shared_with.sharegroup_count`).
     * 
     */
    @Import(name="sharedWith", required=true)
    private GetConsumerImageShareGroupImageSharesImageShareImageSharingSharedWith sharedWith;

    /**
     * @return (Nested Attribute) Details about who the image is shared with. Referenced directly (e.g. `shared_with.sharegroup_count`).
     * 
     */
    public GetConsumerImageShareGroupImageSharesImageShareImageSharingSharedWith sharedWith() {
        return this.sharedWith;
    }

    private GetConsumerImageShareGroupImageSharesImageShareImageSharing() {}

    private GetConsumerImageShareGroupImageSharesImageShareImageSharing(GetConsumerImageShareGroupImageSharesImageShareImageSharing $) {
        this.sharedBy = $.sharedBy;
        this.sharedWith = $.sharedWith;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetConsumerImageShareGroupImageSharesImageShareImageSharing defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetConsumerImageShareGroupImageSharesImageShareImageSharing $;

        public Builder() {
            $ = new GetConsumerImageShareGroupImageSharesImageShareImageSharing();
        }

        public Builder(GetConsumerImageShareGroupImageSharesImageShareImageSharing defaults) {
            $ = new GetConsumerImageShareGroupImageSharesImageShareImageSharing(Objects.requireNonNull(defaults));
        }

        /**
         * @param sharedBy (Nested Attribute) Details about who the image is shared by. Referenced directly (e.g. `shared_by.sharegroup_id`).
         * 
         * @return builder
         * 
         */
        public Builder sharedBy(GetConsumerImageShareGroupImageSharesImageShareImageSharingSharedBy sharedBy) {
            $.sharedBy = sharedBy;
            return this;
        }

        /**
         * @param sharedWith (Nested Attribute) Details about who the image is shared with. Referenced directly (e.g. `shared_with.sharegroup_count`).
         * 
         * @return builder
         * 
         */
        public Builder sharedWith(GetConsumerImageShareGroupImageSharesImageShareImageSharingSharedWith sharedWith) {
            $.sharedWith = sharedWith;
            return this;
        }

        public GetConsumerImageShareGroupImageSharesImageShareImageSharing build() {
            if ($.sharedBy == null) {
                throw new MissingRequiredPropertyException("GetConsumerImageShareGroupImageSharesImageShareImageSharing", "sharedBy");
            }
            if ($.sharedWith == null) {
                throw new MissingRequiredPropertyException("GetConsumerImageShareGroupImageSharesImageShareImageSharing", "sharedWith");
            }
            return $;
        }
    }

}
