// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.linode.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.linode.inputs.GetInstanceTypesTypeAddonBackupPrice;
import com.pulumi.linode.inputs.GetInstanceTypesTypeAddonBackupRegionPrice;
import java.util.List;
import java.util.Objects;


public final class GetInstanceTypesTypeAddonBackup extends com.pulumi.resources.InvokeArgs {

    public static final GetInstanceTypesTypeAddonBackup Empty = new GetInstanceTypesTypeAddonBackup();

    @Import(name="prices", required=true)
    private List<GetInstanceTypesTypeAddonBackupPrice> prices;

    public List<GetInstanceTypesTypeAddonBackupPrice> prices() {
        return this.prices;
    }

    @Import(name="regionPrices", required=true)
    private List<GetInstanceTypesTypeAddonBackupRegionPrice> regionPrices;

    public List<GetInstanceTypesTypeAddonBackupRegionPrice> regionPrices() {
        return this.regionPrices;
    }

    private GetInstanceTypesTypeAddonBackup() {}

    private GetInstanceTypesTypeAddonBackup(GetInstanceTypesTypeAddonBackup $) {
        this.prices = $.prices;
        this.regionPrices = $.regionPrices;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetInstanceTypesTypeAddonBackup defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetInstanceTypesTypeAddonBackup $;

        public Builder() {
            $ = new GetInstanceTypesTypeAddonBackup();
        }

        public Builder(GetInstanceTypesTypeAddonBackup defaults) {
            $ = new GetInstanceTypesTypeAddonBackup(Objects.requireNonNull(defaults));
        }

        public Builder prices(List<GetInstanceTypesTypeAddonBackupPrice> prices) {
            $.prices = prices;
            return this;
        }

        public Builder prices(GetInstanceTypesTypeAddonBackupPrice... prices) {
            return prices(List.of(prices));
        }

        public Builder regionPrices(List<GetInstanceTypesTypeAddonBackupRegionPrice> regionPrices) {
            $.regionPrices = regionPrices;
            return this;
        }

        public Builder regionPrices(GetInstanceTypesTypeAddonBackupRegionPrice... regionPrices) {
            return regionPrices(List.of(regionPrices));
        }

        public GetInstanceTypesTypeAddonBackup build() {
            if ($.prices == null) {
                throw new MissingRequiredPropertyException("GetInstanceTypesTypeAddonBackup", "prices");
            }
            if ($.regionPrices == null) {
                throw new MissingRequiredPropertyException("GetInstanceTypesTypeAddonBackup", "regionPrices");
            }
            return $;
        }
    }

}
