// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.linode.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.linode.inputs.GetLkeVersionsVersionArgs;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetLkeVersionsArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetLkeVersionsArgs Empty = new GetLkeVersionsArgs();

    /**
     * The tier (`standard` or `enterprise`) of Linode LKE Versions to fetch.
     * 
     */
    @Import(name="tier")
    private @Nullable Output<String> tier;

    /**
     * @return The tier (`standard` or `enterprise`) of Linode LKE Versions to fetch.
     * 
     */
    public Optional<Output<String>> tier() {
        return Optional.ofNullable(this.tier);
    }

    @Import(name="versions")
    private @Nullable Output<List<GetLkeVersionsVersionArgs>> versions;

    public Optional<Output<List<GetLkeVersionsVersionArgs>>> versions() {
        return Optional.ofNullable(this.versions);
    }

    private GetLkeVersionsArgs() {}

    private GetLkeVersionsArgs(GetLkeVersionsArgs $) {
        this.tier = $.tier;
        this.versions = $.versions;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetLkeVersionsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetLkeVersionsArgs $;

        public Builder() {
            $ = new GetLkeVersionsArgs();
        }

        public Builder(GetLkeVersionsArgs defaults) {
            $ = new GetLkeVersionsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param tier The tier (`standard` or `enterprise`) of Linode LKE Versions to fetch.
         * 
         * @return builder
         * 
         */
        public Builder tier(@Nullable Output<String> tier) {
            $.tier = tier;
            return this;
        }

        /**
         * @param tier The tier (`standard` or `enterprise`) of Linode LKE Versions to fetch.
         * 
         * @return builder
         * 
         */
        public Builder tier(String tier) {
            return tier(Output.of(tier));
        }

        public Builder versions(@Nullable Output<List<GetLkeVersionsVersionArgs>> versions) {
            $.versions = versions;
            return this;
        }

        public Builder versions(List<GetLkeVersionsVersionArgs> versions) {
            return versions(Output.of(versions));
        }

        public Builder versions(GetLkeVersionsVersionArgs... versions) {
            return versions(List.of(versions));
        }

        public GetLkeVersionsArgs build() {
            return $;
        }
    }

}
