// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.linode.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetObjectStorageEndpointsEndpointArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetObjectStorageEndpointsEndpointArgs Empty = new GetObjectStorageEndpointsEndpointArgs();

    /**
     * The type of `s3_endpoint` available to the active `user`. See [Endpoint types](https://techdocs.akamai.com/cloud-computing/docs/object-storage#endpoint-type) for more information.
     * 
     */
    @Import(name="endpointType", required=true)
    private Output<String> endpointType;

    /**
     * @return The type of `s3_endpoint` available to the active `user`. See [Endpoint types](https://techdocs.akamai.com/cloud-computing/docs/object-storage#endpoint-type) for more information.
     * 
     */
    public Output<String> endpointType() {
        return this.endpointType;
    }

    /**
     * The Akamai cloud computing region, represented by its slug value. The [list regions](https://techdocs.akamai.com/linode-api/reference/get-regions) API is available to see all regions available.
     * 
     */
    @Import(name="region", required=true)
    private Output<String> region;

    /**
     * @return The Akamai cloud computing region, represented by its slug value. The [list regions](https://techdocs.akamai.com/linode-api/reference/get-regions) API is available to see all regions available.
     * 
     */
    public Output<String> region() {
        return this.region;
    }

    /**
     * Your s3 endpoint URL, based on the `endpoint_type` and `region`. Output as null if you haven&#39;t assigned an endpoint for your user in this region with the specific endpoint type.
     * 
     */
    @Import(name="s3Endpoint", required=true)
    private Output<String> s3Endpoint;

    /**
     * @return Your s3 endpoint URL, based on the `endpoint_type` and `region`. Output as null if you haven&#39;t assigned an endpoint for your user in this region with the specific endpoint type.
     * 
     */
    public Output<String> s3Endpoint() {
        return this.s3Endpoint;
    }

    private GetObjectStorageEndpointsEndpointArgs() {}

    private GetObjectStorageEndpointsEndpointArgs(GetObjectStorageEndpointsEndpointArgs $) {
        this.endpointType = $.endpointType;
        this.region = $.region;
        this.s3Endpoint = $.s3Endpoint;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetObjectStorageEndpointsEndpointArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetObjectStorageEndpointsEndpointArgs $;

        public Builder() {
            $ = new GetObjectStorageEndpointsEndpointArgs();
        }

        public Builder(GetObjectStorageEndpointsEndpointArgs defaults) {
            $ = new GetObjectStorageEndpointsEndpointArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param endpointType The type of `s3_endpoint` available to the active `user`. See [Endpoint types](https://techdocs.akamai.com/cloud-computing/docs/object-storage#endpoint-type) for more information.
         * 
         * @return builder
         * 
         */
        public Builder endpointType(Output<String> endpointType) {
            $.endpointType = endpointType;
            return this;
        }

        /**
         * @param endpointType The type of `s3_endpoint` available to the active `user`. See [Endpoint types](https://techdocs.akamai.com/cloud-computing/docs/object-storage#endpoint-type) for more information.
         * 
         * @return builder
         * 
         */
        public Builder endpointType(String endpointType) {
            return endpointType(Output.of(endpointType));
        }

        /**
         * @param region The Akamai cloud computing region, represented by its slug value. The [list regions](https://techdocs.akamai.com/linode-api/reference/get-regions) API is available to see all regions available.
         * 
         * @return builder
         * 
         */
        public Builder region(Output<String> region) {
            $.region = region;
            return this;
        }

        /**
         * @param region The Akamai cloud computing region, represented by its slug value. The [list regions](https://techdocs.akamai.com/linode-api/reference/get-regions) API is available to see all regions available.
         * 
         * @return builder
         * 
         */
        public Builder region(String region) {
            return region(Output.of(region));
        }

        /**
         * @param s3Endpoint Your s3 endpoint URL, based on the `endpoint_type` and `region`. Output as null if you haven&#39;t assigned an endpoint for your user in this region with the specific endpoint type.
         * 
         * @return builder
         * 
         */
        public Builder s3Endpoint(Output<String> s3Endpoint) {
            $.s3Endpoint = s3Endpoint;
            return this;
        }

        /**
         * @param s3Endpoint Your s3 endpoint URL, based on the `endpoint_type` and `region`. Output as null if you haven&#39;t assigned an endpoint for your user in this region with the specific endpoint type.
         * 
         * @return builder
         * 
         */
        public Builder s3Endpoint(String s3Endpoint) {
            return s3Endpoint(Output.of(s3Endpoint));
        }

        public GetObjectStorageEndpointsEndpointArgs build() {
            if ($.endpointType == null) {
                throw new MissingRequiredPropertyException("GetObjectStorageEndpointsEndpointArgs", "endpointType");
            }
            if ($.region == null) {
                throw new MissingRequiredPropertyException("GetObjectStorageEndpointsEndpointArgs", "region");
            }
            if ($.s3Endpoint == null) {
                throw new MissingRequiredPropertyException("GetObjectStorageEndpointsEndpointArgs", "s3Endpoint");
            }
            return $;
        }
    }

}
