// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.linode.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.linode.inputs.InstanceBackupScheduleArgs;
import java.lang.Boolean;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class InstanceBackupArgs extends com.pulumi.resources.ResourceArgs {

    public static final InstanceBackupArgs Empty = new InstanceBackupArgs();

    /**
     * Whether this Backup is available for restoration.
     * 
     */
    @Import(name="available")
    private @Nullable Output<Boolean> available;

    /**
     * @return Whether this Backup is available for restoration.
     * 
     */
    public Optional<Output<Boolean>> available() {
        return Optional.ofNullable(this.available);
    }

    /**
     * If this Linode has the Backup service enabled.
     * 
     */
    @Import(name="enabled")
    private @Nullable Output<Boolean> enabled;

    /**
     * @return If this Linode has the Backup service enabled.
     * 
     */
    public Optional<Output<Boolean>> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    @Import(name="schedules")
    private @Nullable Output<List<InstanceBackupScheduleArgs>> schedules;

    public Optional<Output<List<InstanceBackupScheduleArgs>>> schedules() {
        return Optional.ofNullable(this.schedules);
    }

    private InstanceBackupArgs() {}

    private InstanceBackupArgs(InstanceBackupArgs $) {
        this.available = $.available;
        this.enabled = $.enabled;
        this.schedules = $.schedules;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(InstanceBackupArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private InstanceBackupArgs $;

        public Builder() {
            $ = new InstanceBackupArgs();
        }

        public Builder(InstanceBackupArgs defaults) {
            $ = new InstanceBackupArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param available Whether this Backup is available for restoration.
         * 
         * @return builder
         * 
         */
        public Builder available(@Nullable Output<Boolean> available) {
            $.available = available;
            return this;
        }

        /**
         * @param available Whether this Backup is available for restoration.
         * 
         * @return builder
         * 
         */
        public Builder available(Boolean available) {
            return available(Output.of(available));
        }

        /**
         * @param enabled If this Linode has the Backup service enabled.
         * 
         * @return builder
         * 
         */
        public Builder enabled(@Nullable Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        /**
         * @param enabled If this Linode has the Backup service enabled.
         * 
         * @return builder
         * 
         */
        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        public Builder schedules(@Nullable Output<List<InstanceBackupScheduleArgs>> schedules) {
            $.schedules = schedules;
            return this;
        }

        public Builder schedules(List<InstanceBackupScheduleArgs> schedules) {
            return schedules(Output.of(schedules));
        }

        public Builder schedules(InstanceBackupScheduleArgs... schedules) {
            return schedules(List.of(schedules));
        }

        public InstanceBackupArgs build() {
            return $;
        }
    }

}
