// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.linode.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Integer;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class MonitorLogsStreamDetailsArgs extends com.pulumi.resources.ResourceArgs {

    public static final MonitorLogsStreamDetailsArgs Empty = new MonitorLogsStreamDetailsArgs();

    /**
     * The list of LKE cluster IDs to include in this stream.
     * 
     */
    @Import(name="clusterIds")
    private @Nullable Output<List<Integer>> clusterIds;

    /**
     * @return The list of LKE cluster IDs to include in this stream.
     * 
     */
    public Optional<Output<List<Integer>>> clusterIds() {
        return Optional.ofNullable(this.clusterIds);
    }

    /**
     * When true, all LKE clusters are automatically added to this stream.
     * 
     */
    @Import(name="isAutoAddAllClustersEnabled")
    private @Nullable Output<Boolean> isAutoAddAllClustersEnabled;

    /**
     * @return When true, all LKE clusters are automatically added to this stream.
     * 
     */
    public Optional<Output<Boolean>> isAutoAddAllClustersEnabled() {
        return Optional.ofNullable(this.isAutoAddAllClustersEnabled);
    }

    private MonitorLogsStreamDetailsArgs() {}

    private MonitorLogsStreamDetailsArgs(MonitorLogsStreamDetailsArgs $) {
        this.clusterIds = $.clusterIds;
        this.isAutoAddAllClustersEnabled = $.isAutoAddAllClustersEnabled;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(MonitorLogsStreamDetailsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private MonitorLogsStreamDetailsArgs $;

        public Builder() {
            $ = new MonitorLogsStreamDetailsArgs();
        }

        public Builder(MonitorLogsStreamDetailsArgs defaults) {
            $ = new MonitorLogsStreamDetailsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param clusterIds The list of LKE cluster IDs to include in this stream.
         * 
         * @return builder
         * 
         */
        public Builder clusterIds(@Nullable Output<List<Integer>> clusterIds) {
            $.clusterIds = clusterIds;
            return this;
        }

        /**
         * @param clusterIds The list of LKE cluster IDs to include in this stream.
         * 
         * @return builder
         * 
         */
        public Builder clusterIds(List<Integer> clusterIds) {
            return clusterIds(Output.of(clusterIds));
        }

        /**
         * @param clusterIds The list of LKE cluster IDs to include in this stream.
         * 
         * @return builder
         * 
         */
        public Builder clusterIds(Integer... clusterIds) {
            return clusterIds(List.of(clusterIds));
        }

        /**
         * @param isAutoAddAllClustersEnabled When true, all LKE clusters are automatically added to this stream.
         * 
         * @return builder
         * 
         */
        public Builder isAutoAddAllClustersEnabled(@Nullable Output<Boolean> isAutoAddAllClustersEnabled) {
            $.isAutoAddAllClustersEnabled = isAutoAddAllClustersEnabled;
            return this;
        }

        /**
         * @param isAutoAddAllClustersEnabled When true, all LKE clusters are automatically added to this stream.
         * 
         * @return builder
         * 
         */
        public Builder isAutoAddAllClustersEnabled(Boolean isAutoAddAllClustersEnabled) {
            return isAutoAddAllClustersEnabled(Output.of(isAutoAddAllClustersEnabled));
        }

        public MonitorLogsStreamDetailsArgs build() {
            return $;
        }
    }

}
