// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Linode.Outputs
{

    [OutputType]
    public sealed class GetInterfaceVpcIpv6Result
    {
        /// <summary>
        /// Indicates whether the IPv6 configuration on the Linode interface is public.
        /// </summary>
        public readonly bool IsPublic;
        /// <summary>
        /// IPv6 ranges assigned to this VPC interface.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetInterfaceVpcIpv6RangeResult> Ranges;
        /// <summary>
        /// IPv6 SLAAC address ranges.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetInterfaceVpcIpv6SlaacResult> Slaacs;

        [OutputConstructor]
        private GetInterfaceVpcIpv6Result(
            bool isPublic,

            ImmutableArray<Outputs.GetInterfaceVpcIpv6RangeResult> ranges,

            ImmutableArray<Outputs.GetInterfaceVpcIpv6SlaacResult> slaacs)
        {
            IsPublic = isPublic;
            Ranges = ranges;
            Slaacs = slaacs;
        }
    }
}
