// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Linode.Outputs
{

    [OutputType]
    public sealed class GetInstancesInstanceConfigDeviceSdfResult
    {
        /// <summary>
        /// The Disk ID of the associated `DiskLabel`, if used
        /// </summary>
        public readonly int DiskId;
        /// <summary>
        /// The `Label` of the `Disk` to map to this `Device` slot.
        /// </summary>
        public readonly string? DiskLabel;
        /// <summary>
        /// The Volume ID to map to this `Device` slot.
        /// </summary>
        public readonly int? VolumeId;

        [OutputConstructor]
        private GetInstancesInstanceConfigDeviceSdfResult(
            int diskId,

            string? diskLabel,

            int? volumeId)
        {
            DiskId = diskId;
            DiskLabel = diskLabel;
            VolumeId = volumeId;
        }
    }
}
