// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Linode.Outputs
{

    [OutputType]
    public sealed class GetLkeNodePoolAutoscalerResult
    {
        /// <summary>
        /// Whether autoscaling is enabled for this node pool.
        /// </summary>
        public readonly bool Enabled;
        /// <summary>
        /// The maximum number of nodes to autoscale to.
        /// </summary>
        public readonly int Max;
        /// <summary>
        /// The minimum number of nodes to autoscale to.
        /// </summary>
        public readonly int Min;

        [OutputConstructor]
        private GetLkeNodePoolAutoscalerResult(
            bool enabled,

            int max,

            int min)
        {
            Enabled = enabled;
            Max = max;
            Min = min;
        }
    }
}
