// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Linode.Outputs
{

    [OutputType]
    public sealed class GetMonitorAlertDefinitionEntitiesEntityResult
    {
        /// <summary>
        /// The unique identifier for this entity.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The label of this entity.
        /// </summary>
        public readonly string Label;
        /// <summary>
        /// The type of this entity.
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// The URL for this entity.
        /// </summary>
        public readonly string Url;

        [OutputConstructor]
        private GetMonitorAlertDefinitionEntitiesEntityResult(
            string id,

            string label,

            string type,

            string url)
        {
            Id = id;
            Label = label;
            Type = type;
            Url = url;
        }
    }
}
