// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Linode.Outputs
{

    [OutputType]
    public sealed class GetNetworkTransferPricesTypeResult
    {
        /// <summary>
        /// The ID representing the Network Transfer Price.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The Network Transfer Price label is for display purposes only.
        /// </summary>
        public readonly string Label;
        /// <summary>
        /// Cost in US dollars, broken down into hourly and monthly charges.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetNetworkTransferPricesTypePriceResult> Prices;
        /// <summary>
        /// A list of region-specific prices for this Network Transfer Price.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetNetworkTransferPricesTypeRegionPriceResult> RegionPrices;
        /// <summary>
        /// The monthly outbound transfer amount, in MB.
        /// </summary>
        public readonly int Transfer;

        [OutputConstructor]
        private GetNetworkTransferPricesTypeResult(
            string id,

            string label,

            ImmutableArray<Outputs.GetNetworkTransferPricesTypePriceResult> prices,

            ImmutableArray<Outputs.GetNetworkTransferPricesTypeRegionPriceResult> regionPrices,

            int transfer)
        {
            Id = id;
            Label = label;
            Prices = prices;
            RegionPrices = regionPrices;
            Transfer = transfer;
        }
    }
}
