// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Linode.Outputs
{

    [OutputType]
    public sealed class GetVolumeTypesTypeResult
    {
        /// <summary>
        /// The ID representing the Volume type.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The Volume type label is for display purposes only.
        /// </summary>
        public readonly string Label;
        /// <summary>
        /// (Read-Only Object List) Pricing information for this Linode Volume type. Referenced with an index (e.g. `price.0.hourly`).
        /// </summary>
        public readonly ImmutableArray<Outputs.GetVolumeTypesTypePriceResult> Prices;
        /// <summary>
        /// (Read-Only Object List) Region-specific pricing information for this Linode Volume type. Referenced with an index (e.g. `region_prices.0.hourly`).
        /// </summary>
        public readonly ImmutableArray<Outputs.GetVolumeTypesTypeRegionPriceResult> RegionPrices;
        /// <summary>
        /// The monthly outbound transfer amount, in MB.
        /// </summary>
        public readonly int Transfer;

        [OutputConstructor]
        private GetVolumeTypesTypeResult(
            string id,

            string label,

            ImmutableArray<Outputs.GetVolumeTypesTypePriceResult> prices,

            ImmutableArray<Outputs.GetVolumeTypesTypeRegionPriceResult> regionPrices,

            int transfer)
        {
            Id = id;
            Label = label;
            Prices = prices;
            RegionPrices = regionPrices;
            Transfer = transfer;
        }
    }
}
