// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Linode.Outputs
{

    [OutputType]
    public sealed class GetVpcSubnetsVpcSubnetDatabaseResult
    {
        /// <summary>
        /// ID of a managed database assigned to the VPC Subnet.
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// IPv4 range assigned to the database.
        /// </summary>
        public readonly string Ipv4Range;
        /// <summary>
        /// A list of IPv6 ranges assigned to the database.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetVpcSubnetsVpcSubnetDatabaseIpv6RangeResult> Ipv6Ranges;

        [OutputConstructor]
        private GetVpcSubnetsVpcSubnetDatabaseResult(
            int id,

            string ipv4Range,

            ImmutableArray<Outputs.GetVpcSubnetsVpcSubnetDatabaseIpv6RangeResult> ipv6Ranges)
        {
            Id = id;
            Ipv4Range = ipv4Range;
            Ipv6Ranges = ipv6Ranges;
        }
    }
}
