// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Linode.Outputs
{

    [OutputType]
    public sealed class InstanceConfigDevices
    {
        public readonly Outputs.InstanceConfigDevicesSda? Sda;
        public readonly Outputs.InstanceConfigDevicesSdb? Sdb;
        public readonly Outputs.InstanceConfigDevicesSdc? Sdc;
        public readonly Outputs.InstanceConfigDevicesSdd? Sdd;
        public readonly Outputs.InstanceConfigDevicesSde? Sde;
        public readonly Outputs.InstanceConfigDevicesSdf? Sdf;
        public readonly Outputs.InstanceConfigDevicesSdg? Sdg;
        public readonly Outputs.InstanceConfigDevicesSdh? Sdh;

        [OutputConstructor]
        private InstanceConfigDevices(
            Outputs.InstanceConfigDevicesSda? sda,

            Outputs.InstanceConfigDevicesSdb? sdb,

            Outputs.InstanceConfigDevicesSdc? sdc,

            Outputs.InstanceConfigDevicesSdd? sdd,

            Outputs.InstanceConfigDevicesSde? sde,

            Outputs.InstanceConfigDevicesSdf? sdf,

            Outputs.InstanceConfigDevicesSdg? sdg,

            Outputs.InstanceConfigDevicesSdh? sdh)
        {
            Sda = sda;
            Sdb = sdb;
            Sdc = sdc;
            Sdd = sdd;
            Sde = sde;
            Sdf = sdf;
            Sdg = sdg;
            Sdh = sdh;
        }
    }
}
