// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Linode.Outputs
{

    [OutputType]
    public sealed class VpcSubnetLinodeInterface
    {
        /// <summary>
        /// Whether the Interface is actively in use.
        /// </summary>
        public readonly bool Active;
        /// <summary>
        /// ID of Linode Config that the interface is associated with. `Null` for a Linode Interface.
        /// </summary>
        public readonly int ConfigId;
        /// <summary>
        /// ID of the interface.
        /// </summary>
        public readonly int Id;

        [OutputConstructor]
        private VpcSubnetLinodeInterface(
            bool active,

            int configId,

            int id)
        {
            Active = active;
            ConfigId = configId;
            Id = id;
        }
    }
}
