// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package linode

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-linode/sdk/v5/go/linode/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Provides details about an LKE Cluster.
// For more information, see the [Linode APIv4 docs](https://techdocs.akamai.com/linode-api/reference/get-lke-cluster).
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-linode/sdk/v5/go/linode"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := linode.LookupLkeCluster(ctx, &linode.LookupLkeClusterArgs{
//				Id: 123,
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupLkeCluster(ctx *pulumi.Context, args *LookupLkeClusterArgs, opts ...pulumi.InvokeOption) (*LookupLkeClusterResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupLkeClusterResult
	err := ctx.Invoke("linode:index/getLkeCluster:getLkeCluster", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getLkeCluster.
type LookupLkeClusterArgs struct {
	// The settings for the Kubernetes Control Plane.
	ControlPlanes []GetLkeClusterControlPlane `pulumi:"controlPlanes"`
	// The LKE Cluster's ID.
	Id int `pulumi:"id"`
	// Node pools associated with this cluster.
	Pools []GetLkeClusterPool `pulumi:"pools"`
}

// A collection of values returned by getLkeCluster.
type LookupLkeClusterResult struct {
	// The endpoints for the Kubernetes API server.
	ApiEndpoints []string `pulumi:"apiEndpoints"`
	// Enables the App Platform Layer
	AplEnabled bool `pulumi:"aplEnabled"`
	// The settings for the Kubernetes Control Plane.
	ControlPlanes []GetLkeClusterControlPlane `pulumi:"controlPlanes"`
	// When this Kubernetes cluster was created.
	Created string `pulumi:"created"`
	// The Kubernetes Dashboard access URL for this cluster. LKE Enterprise does not have a dashboard URL.
	DashboardUrl string `pulumi:"dashboardUrl"`
	// The ID of the node.
	Id int `pulumi:"id"`
	// The k8s version of the nodes in this Node Pool. For LKE enterprise only and may not currently available to all users even under v4beta.
	K8sVersion string `pulumi:"k8sVersion"`
	// The base64 encoded kubeconfig for the Kubernetes cluster.
	Kubeconfig string `pulumi:"kubeconfig"`
	// The label of the Node Pool.
	Label string `pulumi:"label"`
	// Node pools associated with this cluster.
	Pools []GetLkeClusterPool `pulumi:"pools"`
	// This Kubernetes cluster's location.
	Region string `pulumi:"region"`
	// The status of the node. (`ready`, `notReady`)
	Status string `pulumi:"status"`
	// An array of tags applied to this object. Tags are case-insensitive and are for organizational purposes only.
	Tags []string `pulumi:"tags"`
	// The desired Kubernetes tier. (**Note: v4beta only and may not currently be available to all users.**)
	Tier string `pulumi:"tier"`
	// When this Kubernetes cluster was updated.
	Updated string `pulumi:"updated"`
}

func LookupLkeClusterOutput(ctx *pulumi.Context, args LookupLkeClusterOutputArgs, opts ...pulumi.InvokeOption) LookupLkeClusterResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupLkeClusterResultOutput, error) {
			args := v.(LookupLkeClusterArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("linode:index/getLkeCluster:getLkeCluster", args, LookupLkeClusterResultOutput{}, options).(LookupLkeClusterResultOutput), nil
		}).(LookupLkeClusterResultOutput)
}

// A collection of arguments for invoking getLkeCluster.
type LookupLkeClusterOutputArgs struct {
	// The settings for the Kubernetes Control Plane.
	ControlPlanes GetLkeClusterControlPlaneArrayInput `pulumi:"controlPlanes"`
	// The LKE Cluster's ID.
	Id pulumi.IntInput `pulumi:"id"`
	// Node pools associated with this cluster.
	Pools GetLkeClusterPoolArrayInput `pulumi:"pools"`
}

func (LookupLkeClusterOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupLkeClusterArgs)(nil)).Elem()
}

// A collection of values returned by getLkeCluster.
type LookupLkeClusterResultOutput struct{ *pulumi.OutputState }

func (LookupLkeClusterResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupLkeClusterResult)(nil)).Elem()
}

func (o LookupLkeClusterResultOutput) ToLookupLkeClusterResultOutput() LookupLkeClusterResultOutput {
	return o
}

func (o LookupLkeClusterResultOutput) ToLookupLkeClusterResultOutputWithContext(ctx context.Context) LookupLkeClusterResultOutput {
	return o
}

// The endpoints for the Kubernetes API server.
func (o LookupLkeClusterResultOutput) ApiEndpoints() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupLkeClusterResult) []string { return v.ApiEndpoints }).(pulumi.StringArrayOutput)
}

// Enables the App Platform Layer
func (o LookupLkeClusterResultOutput) AplEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupLkeClusterResult) bool { return v.AplEnabled }).(pulumi.BoolOutput)
}

// The settings for the Kubernetes Control Plane.
func (o LookupLkeClusterResultOutput) ControlPlanes() GetLkeClusterControlPlaneArrayOutput {
	return o.ApplyT(func(v LookupLkeClusterResult) []GetLkeClusterControlPlane { return v.ControlPlanes }).(GetLkeClusterControlPlaneArrayOutput)
}

// When this Kubernetes cluster was created.
func (o LookupLkeClusterResultOutput) Created() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLkeClusterResult) string { return v.Created }).(pulumi.StringOutput)
}

// The Kubernetes Dashboard access URL for this cluster. LKE Enterprise does not have a dashboard URL.
func (o LookupLkeClusterResultOutput) DashboardUrl() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLkeClusterResult) string { return v.DashboardUrl }).(pulumi.StringOutput)
}

// The ID of the node.
func (o LookupLkeClusterResultOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v LookupLkeClusterResult) int { return v.Id }).(pulumi.IntOutput)
}

// The k8s version of the nodes in this Node Pool. For LKE enterprise only and may not currently available to all users even under v4beta.
func (o LookupLkeClusterResultOutput) K8sVersion() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLkeClusterResult) string { return v.K8sVersion }).(pulumi.StringOutput)
}

// The base64 encoded kubeconfig for the Kubernetes cluster.
func (o LookupLkeClusterResultOutput) Kubeconfig() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLkeClusterResult) string { return v.Kubeconfig }).(pulumi.StringOutput)
}

// The label of the Node Pool.
func (o LookupLkeClusterResultOutput) Label() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLkeClusterResult) string { return v.Label }).(pulumi.StringOutput)
}

// Node pools associated with this cluster.
func (o LookupLkeClusterResultOutput) Pools() GetLkeClusterPoolArrayOutput {
	return o.ApplyT(func(v LookupLkeClusterResult) []GetLkeClusterPool { return v.Pools }).(GetLkeClusterPoolArrayOutput)
}

// This Kubernetes cluster's location.
func (o LookupLkeClusterResultOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLkeClusterResult) string { return v.Region }).(pulumi.StringOutput)
}

// The status of the node. (`ready`, `notReady`)
func (o LookupLkeClusterResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLkeClusterResult) string { return v.Status }).(pulumi.StringOutput)
}

// An array of tags applied to this object. Tags are case-insensitive and are for organizational purposes only.
func (o LookupLkeClusterResultOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupLkeClusterResult) []string { return v.Tags }).(pulumi.StringArrayOutput)
}

// The desired Kubernetes tier. (**Note: v4beta only and may not currently be available to all users.**)
func (o LookupLkeClusterResultOutput) Tier() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLkeClusterResult) string { return v.Tier }).(pulumi.StringOutput)
}

// When this Kubernetes cluster was updated.
func (o LookupLkeClusterResultOutput) Updated() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLkeClusterResult) string { return v.Updated }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupLkeClusterResultOutput{})
}
