// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package linode

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-linode/sdk/v4/go/linode/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Provides details about Object Storage quota information on your account.
// For more information, see the Linode APIv4 docs.
//
// ## Example Usage
//
// The following example shows how one might use this data source to access information about an Object Storage quota.
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-linode/sdk/v4/go/linode"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := linode.GetObjectStorageQuota(ctx, &linode.GetObjectStorageQuotaArgs{
//				QuotaId: "obj-buckets-br-gru-1.linodeobjects.com",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetObjectStorageQuota(ctx *pulumi.Context, args *GetObjectStorageQuotaArgs, opts ...pulumi.InvokeOption) (*GetObjectStorageQuotaResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetObjectStorageQuotaResult
	err := ctx.Invoke("linode:index/getObjectStorageQuota:getObjectStorageQuota", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getObjectStorageQuota.
type GetObjectStorageQuotaArgs struct {
	// The Object Storage quota ID.
	QuotaId string `pulumi:"quotaId"`
}

// A collection of values returned by getObjectStorageQuota.
type GetObjectStorageQuotaResult struct {
	// The description of the Object Storage quota.
	Description string `pulumi:"description"`
	// The type of the S3 endpoint of the Object Storage.
	EndpointType string `pulumi:"endpointType"`
	// The unique ID of the Object Storage quota data source.
	Id      string `pulumi:"id"`
	QuotaId string `pulumi:"quotaId"`
	// The maximum quantity allowed by the quota.
	QuotaLimit int `pulumi:"quotaLimit"`
	// The name of the Object Storage quota.
	QuotaName string `pulumi:"quotaName"`
	// The usage data for a specific Object Storage related quota on your account.
	QuotaUsage GetObjectStorageQuotaQuotaUsage `pulumi:"quotaUsage"`
	// The specific Object Storage resource for the quota.
	ResourceMetric string `pulumi:"resourceMetric"`
	// The S3 endpoint URL of the Object Storage, based on the `endpointType` and `region`.
	S3Endpoint string `pulumi:"s3Endpoint"`
}

func GetObjectStorageQuotaOutput(ctx *pulumi.Context, args GetObjectStorageQuotaOutputArgs, opts ...pulumi.InvokeOption) GetObjectStorageQuotaResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetObjectStorageQuotaResultOutput, error) {
			args := v.(GetObjectStorageQuotaArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("linode:index/getObjectStorageQuota:getObjectStorageQuota", args, GetObjectStorageQuotaResultOutput{}, options).(GetObjectStorageQuotaResultOutput), nil
		}).(GetObjectStorageQuotaResultOutput)
}

// A collection of arguments for invoking getObjectStorageQuota.
type GetObjectStorageQuotaOutputArgs struct {
	// The Object Storage quota ID.
	QuotaId pulumi.StringInput `pulumi:"quotaId"`
}

func (GetObjectStorageQuotaOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetObjectStorageQuotaArgs)(nil)).Elem()
}

// A collection of values returned by getObjectStorageQuota.
type GetObjectStorageQuotaResultOutput struct{ *pulumi.OutputState }

func (GetObjectStorageQuotaResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetObjectStorageQuotaResult)(nil)).Elem()
}

func (o GetObjectStorageQuotaResultOutput) ToGetObjectStorageQuotaResultOutput() GetObjectStorageQuotaResultOutput {
	return o
}

func (o GetObjectStorageQuotaResultOutput) ToGetObjectStorageQuotaResultOutputWithContext(ctx context.Context) GetObjectStorageQuotaResultOutput {
	return o
}

// The description of the Object Storage quota.
func (o GetObjectStorageQuotaResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetObjectStorageQuotaResult) string { return v.Description }).(pulumi.StringOutput)
}

// The type of the S3 endpoint of the Object Storage.
func (o GetObjectStorageQuotaResultOutput) EndpointType() pulumi.StringOutput {
	return o.ApplyT(func(v GetObjectStorageQuotaResult) string { return v.EndpointType }).(pulumi.StringOutput)
}

// The unique ID of the Object Storage quota data source.
func (o GetObjectStorageQuotaResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetObjectStorageQuotaResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetObjectStorageQuotaResultOutput) QuotaId() pulumi.StringOutput {
	return o.ApplyT(func(v GetObjectStorageQuotaResult) string { return v.QuotaId }).(pulumi.StringOutput)
}

// The maximum quantity allowed by the quota.
func (o GetObjectStorageQuotaResultOutput) QuotaLimit() pulumi.IntOutput {
	return o.ApplyT(func(v GetObjectStorageQuotaResult) int { return v.QuotaLimit }).(pulumi.IntOutput)
}

// The name of the Object Storage quota.
func (o GetObjectStorageQuotaResultOutput) QuotaName() pulumi.StringOutput {
	return o.ApplyT(func(v GetObjectStorageQuotaResult) string { return v.QuotaName }).(pulumi.StringOutput)
}

// The usage data for a specific Object Storage related quota on your account.
func (o GetObjectStorageQuotaResultOutput) QuotaUsage() GetObjectStorageQuotaQuotaUsageOutput {
	return o.ApplyT(func(v GetObjectStorageQuotaResult) GetObjectStorageQuotaQuotaUsage { return v.QuotaUsage }).(GetObjectStorageQuotaQuotaUsageOutput)
}

// The specific Object Storage resource for the quota.
func (o GetObjectStorageQuotaResultOutput) ResourceMetric() pulumi.StringOutput {
	return o.ApplyT(func(v GetObjectStorageQuotaResult) string { return v.ResourceMetric }).(pulumi.StringOutput)
}

// The S3 endpoint URL of the Object Storage, based on the `endpointType` and `region`.
func (o GetObjectStorageQuotaResultOutput) S3Endpoint() pulumi.StringOutput {
	return o.ApplyT(func(v GetObjectStorageQuotaResult) string { return v.S3Endpoint }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetObjectStorageQuotaResultOutput{})
}
