// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.linode.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.util.Objects;

@CustomType
public final class GetVpcsVpcSubnetLinodeInterface {
    private Boolean active;
    private Integer configId;
    /**
     * @return The unique id of this VPC.
     * 
     */
    private Integer id;

    private GetVpcsVpcSubnetLinodeInterface() {}
    public Boolean active() {
        return this.active;
    }
    public Integer configId() {
        return this.configId;
    }
    /**
     * @return The unique id of this VPC.
     * 
     */
    public Integer id() {
        return this.id;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetVpcsVpcSubnetLinodeInterface defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Boolean active;
        private Integer configId;
        private Integer id;
        public Builder() {}
        public Builder(GetVpcsVpcSubnetLinodeInterface defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.active = defaults.active;
    	      this.configId = defaults.configId;
    	      this.id = defaults.id;
        }

        @CustomType.Setter
        public Builder active(Boolean active) {
            if (active == null) {
              throw new MissingRequiredPropertyException("GetVpcsVpcSubnetLinodeInterface", "active");
            }
            this.active = active;
            return this;
        }
        @CustomType.Setter
        public Builder configId(Integer configId) {
            if (configId == null) {
              throw new MissingRequiredPropertyException("GetVpcsVpcSubnetLinodeInterface", "configId");
            }
            this.configId = configId;
            return this;
        }
        @CustomType.Setter
        public Builder id(Integer id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetVpcsVpcSubnetLinodeInterface", "id");
            }
            this.id = id;
            return this;
        }
        public GetVpcsVpcSubnetLinodeInterface build() {
            final var _resultValue = new GetVpcsVpcSubnetLinodeInterface();
            _resultValue.active = active;
            _resultValue.configId = configId;
            _resultValue.id = id;
            return _resultValue;
        }
    }
}
