// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Linode.Inputs
{

    public sealed class GetAccountLoginsLoginArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// When the login was initiated.
        /// </summary>
        [Input("datetime", required: true)]
        public string Datetime { get; set; } = null!;

        /// <summary>
        /// The unique ID of this login object.
        /// </summary>
        [Input("id", required: true)]
        public int Id { get; set; }

        /// <summary>
        /// The remote IP address that requested the login.
        /// </summary>
        [Input("ip", required: true)]
        public string Ip { get; set; } = null!;

        /// <summary>
        /// True if the User that was logged into was a restricted User, false otherwise.
        /// </summary>
        [Input("restricted", required: true)]
        public bool Restricted { get; set; }

        [Input("status", required: true)]
        public string Status { get; set; } = null!;

        /// <summary>
        /// The username of the User that was logged into.
        /// </summary>
        [Input("username", required: true)]
        public string Username { get; set; } = null!;

        public GetAccountLoginsLoginArgs()
        {
        }
        public static new GetAccountLoginsLoginArgs Empty => new GetAccountLoginsLoginArgs();
    }
}
