// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Linode.Inputs
{

    public sealed class GetNodebalancersNodebalancerInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Throttle connections per second (0-20)
        /// </summary>
        [Input("clientConnThrottle", required: true)]
        public Input<int> ClientConnThrottle { get; set; } = null!;

        /// <summary>
        /// When this Linode NodeBalancer was created
        /// </summary>
        [Input("created", required: true)]
        public Input<string> Created { get; set; } = null!;

        /// <summary>
        /// This NodeBalancer's hostname, ending with .ip.linodeusercontent.com
        /// </summary>
        [Input("hostname", required: true)]
        public Input<string> Hostname { get; set; } = null!;

        /// <summary>
        /// The Linode NodeBalancer's unique ID
        /// </summary>
        [Input("id", required: true)]
        public Input<int> Id { get; set; } = null!;

        /// <summary>
        /// The Public IPv4 Address of this NodeBalancer
        /// </summary>
        [Input("ipv4", required: true)]
        public Input<string> Ipv4 { get; set; } = null!;

        /// <summary>
        /// The Public IPv6 Address of this NodeBalancer
        /// </summary>
        [Input("ipv6", required: true)]
        public Input<string> Ipv6 { get; set; } = null!;

        /// <summary>
        /// The label of the Linode NodeBalancer
        /// </summary>
        [Input("label", required: true)]
        public Input<string> Label { get; set; } = null!;

        /// <summary>
        /// The Region where this Linode NodeBalancer is located. NodeBalancers only support backends in the same Region.
        /// </summary>
        [Input("region", required: true)]
        public Input<string> Region { get; set; } = null!;

        [Input("tags", required: true)]
        private InputList<string>? _tags;

        /// <summary>
        /// A list of tags applied to this object. Tags are for organizational purposes only.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        [Input("transfers", required: true)]
        private InputList<Inputs.GetNodebalancersNodebalancerTransferInputArgs>? _transfers;

        /// <summary>
        /// Information about the amount of transfer this NodeBalancer has had so far this month.
        /// </summary>
        public InputList<Inputs.GetNodebalancersNodebalancerTransferInputArgs> Transfers
        {
            get => _transfers ?? (_transfers = new InputList<Inputs.GetNodebalancersNodebalancerTransferInputArgs>());
            set => _transfers = value;
        }

        /// <summary>
        /// When this Linode NodeBalancer was last updated
        /// </summary>
        [Input("updated", required: true)]
        public Input<string> Updated { get; set; } = null!;

        public GetNodebalancersNodebalancerInputArgs()
        {
        }
        public static new GetNodebalancersNodebalancerInputArgs Empty => new GetNodebalancersNodebalancerInputArgs();
    }
}
