// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Linode.Inputs
{

    public sealed class InstanceBackupsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether this Backup is available for restoration.
        /// </summary>
        [Input("available")]
        public Input<bool>? Available { get; set; }

        /// <summary>
        /// If this Linode has the Backup service enabled.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        [Input("schedule")]
        public Input<Inputs.InstanceBackupsScheduleArgs>? Schedule { get; set; }

        public InstanceBackupsArgs()
        {
        }
        public static new InstanceBackupsArgs Empty => new InstanceBackupsArgs();
    }
}
