// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Linode.Inputs
{

    public sealed class InterfacePublicIpv6RangeGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The IPv6 range.
        /// </summary>
        [Input("range", required: true)]
        public Input<string> Range { get; set; } = null!;

        /// <summary>
        /// The public IPv6 address that the range is routed to.
        /// </summary>
        [Input("routeTarget")]
        public Input<string>? RouteTarget { get; set; }

        public InterfacePublicIpv6RangeGetArgs()
        {
        }
        public static new InterfacePublicIpv6RangeGetArgs Empty => new InterfacePublicIpv6RangeGetArgs();
    }
}
