// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Linode.Inputs
{

    public sealed class InterfacePublicArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// IPv4 addresses for this interface.
        /// </summary>
        [Input("ipv4")]
        public Input<Inputs.InterfacePublicIpv4Args>? Ipv4 { get; set; }

        /// <summary>
        /// IPv6 addresses for this interface.
        /// </summary>
        [Input("ipv6")]
        public Input<Inputs.InterfacePublicIpv6Args>? Ipv6 { get; set; }

        public InterfacePublicArgs()
        {
        }
        public static new InterfacePublicArgs Empty => new InterfacePublicArgs();
    }
}
