// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Linode.Inputs
{

    public sealed class InterfaceVlanGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The VLAN interface's private IPv4 address in CIDR notation.
        /// </summary>
        [Input("ipamAddress")]
        public Input<string>? IpamAddress { get; set; }

        /// <summary>
        /// The VLAN's unique label. Must be between 1 and 64 characters.
        /// </summary>
        [Input("vlanLabel", required: true)]
        public Input<string> VlanLabel { get; set; } = null!;

        public InterfaceVlanGetArgs()
        {
        }
        public static new InterfaceVlanGetArgs Empty => new InterfaceVlanGetArgs();
    }
}
