// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Provides information about a Linode Tag, including the objects associated with it.
 *
 * For more information, see the [Linode APIv4 documentation](https://techdocs.akamai.com/linode-api/reference/get-tagged-objects).
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as linode from "@pulumi/linode";
 *
 * const example = linode.getTag({
 *     label: "my-tag",
 * });
 * ```
 */
export function getTag(args: GetTagArgs, opts?: pulumi.InvokeOptions): Promise<GetTagResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("linode:index/getTag:getTag", {
        "label": args.label,
    }, opts);
}

/**
 * A collection of arguments for invoking getTag.
 */
export interface GetTagArgs {
    /**
     * The label of the tag to look up.
     */
    label: string;
}

/**
 * A collection of values returned by getTag.
 */
export interface GetTagResult {
    /**
     * The ID of the tagged object. For `reservedIpv4Address` objects, this is the IP address string.
     */
    readonly id: string;
    readonly label: string;
    /**
     * (Nested Attribute List) A list of objects associated with this tag. Each object has the following attributes:
     */
    readonly objects: outputs.GetTagObject[];
}
/**
 * Provides information about a Linode Tag, including the objects associated with it.
 *
 * For more information, see the [Linode APIv4 documentation](https://techdocs.akamai.com/linode-api/reference/get-tagged-objects).
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as linode from "@pulumi/linode";
 *
 * const example = linode.getTag({
 *     label: "my-tag",
 * });
 * ```
 */
export function getTagOutput(args: GetTagOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetTagResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("linode:index/getTag:getTag", {
        "label": args.label,
    }, opts);
}

/**
 * A collection of arguments for invoking getTag.
 */
export interface GetTagOutputArgs {
    /**
     * The label of the tag to look up.
     */
    label: pulumi.Input<string>;
}
